-- h2/schema.sql

DROP TABLE vet_specialties IF EXISTS;
DROP TABLE vets IF EXISTS;
DROP TABLE specialties IF EXISTS;
DROP TABLE visits IF EXISTS;
DROP TABLE pets IF EXISTS;
DROP TABLE types IF EXISTS;
DROP TABLE owners IF EXISTS;


CREATE TABLE vets (
                    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    first_name VARCHAR(30),
                    last_name  VARCHAR(30)
);
CREATE INDEX vets_last_name ON vets (last_name);

CREATE TABLE specialties (
                           id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           name VARCHAR(80)
);
CREATE INDEX specialties_name ON specialties (name);

CREATE TABLE vet_specialties (
                               vet_id       INTEGER NOT NULL,
                               specialty_id INTEGER NOT NULL
);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_vets FOREIGN KEY (vet_id) REFERENCES vets (id);
ALTER TABLE vet_specialties ADD CONSTRAINT fk_vet_specialties_specialties FOREIGN KEY (specialty_id) REFERENCES specialties (id);

CREATE TABLE types (
                     id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     name VARCHAR(80)
);
CREATE INDEX types_name ON types (name);

CREATE TABLE owners (
                      id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      first_name VARCHAR(30),
                      last_name  VARCHAR_IGNORECASE(30),
                      address    VARCHAR(255),
                      city       VARCHAR(80),
                      telephone  VARCHAR(20)
);
CREATE INDEX owners_last_name ON owners (last_name);

CREATE TABLE pets (
                    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name       VARCHAR(30),
                    birth_date DATE,
                    type_id    INTEGER NOT NULL,
                    owner_id   INTEGER
);
ALTER TABLE pets ADD CONSTRAINT fk_pets_owners FOREIGN KEY (owner_id) REFERENCES owners (id);
ALTER TABLE pets ADD CONSTRAINT fk_pets_types FOREIGN KEY (type_id) REFERENCES types (id);
CREATE INDEX pets_name ON pets (name);

CREATE TABLE visits (
                      id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      pet_id      INTEGER,
                      visit_date  DATE,
                      description VARCHAR(255)
);
ALTER TABLE visits ADD CONSTRAINT fk_visits_pets FOREIGN KEY (pet_id) REFERENCES pets (id);
CREATE INDEX visits_pet_id ON visits (pet_id);


-- =====================================================================
-- Patriot Thanks: User Authentication Tables (H2 syntax)
-- Add these to the END of your existing db/h2/schema.sql
-- =====================================================================

CREATE TABLE IF NOT EXISTS patriot_roles (
                                           id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           name       VARCHAR(50) NOT NULL,
                                           description VARCHAR(255),
                                           CONSTRAINT uc_patriot_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS patriot_users (
                                           id             INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                           first_name     VARCHAR(256) NOT NULL,
                                           last_name      VARCHAR(256) NOT NULL,
                                           email          VARCHAR(255) NOT NULL,
                                           password_hash  VARCHAR(255) NOT NULL,
                                           phone          VARCHAR(20),
                                           status_id      INTEGER NOT NULL,
                                           email_verified BOOLEAN DEFAULT FALSE,
                                           created_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                           updated_at     TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                                           deleted_at     TIMESTAMP,
                                           CONSTRAINT uc_patriot_users_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS patriot_user_roles (
                                                patriot_user_id INTEGER NOT NULL,
                                                patriot_role_id INTEGER NOT NULL,
                                                PRIMARY KEY (patriot_user_id, patriot_role_id),
                                                CONSTRAINT fk_pur_user FOREIGN KEY (patriot_user_id) REFERENCES patriot_users (id) ON DELETE CASCADE,
                                                CONSTRAINT fk_pur_role FOREIGN KEY (patriot_role_id) REFERENCES patriot_roles (id) ON DELETE CASCADE
);
